### ISSUE TITLE
How to install Dependencies?

### ISSUE THREAD

**Issue by nstarke** [fiedka/fiedka#26]
Ran into some trouble trying to set up `utk-web`:

* Can you provide instructions on how to install the right MFTCLI version?
* Can you provide instructions on how to install a version of `uefi_firmware` that has the `--json` argument flag?

I will update this ticket with any additional dependency issues I encounter.  Thank you!

**Comment by orangecms** [comment]
Let's go slow on this. :-)

I have to admit that the `mftcli` I am using is a modification I haven't pushed yet - mostly due to lack of understanding of Go modules. There is https://github.com/Mimoja/MFT-AnalyserV2/tree/master/cmd/mftcli which I modified a bit on my local machine. I will publish more on this over time. If you understand Go modules well, I'd appreciate any help!
One core issue I faced was working with changes in other modules that mftcli uses. I would need to swap out dependencies, but actually want to develop in multiple places over time, and eventually upstream things again. That's a bit weird with Go mirroring DNS and web/git URLs.
I actually exchanged a bit with @mimoja but stalled for the time being. Now I had some ideas again and wanted to get back to the project. :-)

**Comment by orangecms** [comment]
Oh, I did push some of my changes. It's actually mentioned in the utk-web README:

https://github.com/orangecms/MFT-AnalyserV2/tree/json

**Comment by orangecms** [comment]
A note on uefi-firmware-parser: For Arch, there is [a package in the AUR](https://aur.archlinux.org/packages/uefi-firmware-parser-git). Otherwise, I would ask you to follow your OS distro's way of installing software, or the main way Python offers for your system, or creating a package yourself, or working with the upstream repository directly. I cannot offer much support for the complexity it implies, unfortunately.

Now regarding mftcli: I have started to work on a [branch for the wasm back-end](https://github.com/orangecms/utk-web/tree/wasm), where I am adding actual Go code to this repository, which will replace mftcli.
There is already code pulling in utk itself. :-)

**Comment by orangecms** [comment]
Update: We now have a fully self-contained app; the prototype as been archived to the `utk-web` branch for reference.
Releases can be downloaded prebuilt for Linux from https://github.com/fiedka/fiedka/releases.

The current code already has capabilities (though limited) to parse and visualize AMD/PSP. Further work needs to be done in https://github.com/linuxboot/fiano which is the tooling for the backend that is running in WASM. Closing this now.

Please let me know if you would like to contribute somewhere, either in the respective issue here or add a new one. Thank you!
